import { mediaUrl } from './api';

// Maps the retailer-safe marketplace DTO into the shape shared by product cards,
// details, and enquiry screens. Internal seller costs are never part of this DTO.
export function mapMarketplaceProduct(product = {}) {
  const prices = product.prices || {};
  const specs = product.specs || {};
  const packing = product.packing || {};
  const classification = product.classification || {};
  const retail = Number(prices.retail_price) || 0;
  const mrp = Number(prices.mrp) || 0;

  return {
    id: product.id || product._id,
    _raw: {
      ...product,
      code: product.code || '',
      name: product.name || '',
      alias: product.alias || '',
      brand_id: product.brand ? { _id: product.brand.id, name: product.brand.name } : null,
      category_id: product.category ? { _id: product.category.id, name: product.category.name } : null,
      sub_category_id: product.sub_category ? { _id: product.sub_category.id, name: product.sub_category.name } : null,
      hsn_code: specs.hsn_code || '',
      size: specs.size || '',
      finish: specs.finish || '',
      material: specs.material || '',
      color: specs.color || '',
      surface: specs.surface || '',
      thickness: specs.thickness || '',
      grade: specs.grade || '',
      tile_type: specs.tile_type || '',
      application: specs.application || '',
      anti_skid: specs.anti_skid || '',
      origin: specs.origin || '',
      manufacturer: specs.manufacturer || '',
      barcode: specs.barcode || '',
      design: specs.design || '',
      collection: specs.collection || '',
      pcs_per_box: packing.pcs_per_box,
      sqft_per_box: packing.sqft_per_box,
      weight_per_box: packing.weight_per_box,
      unit: product.unit || '',
      gst_percent: product.gst_percent,
      description: product.description || '',
      selling_price: prices.selling_price,
      retail_price: prices.retail_price,
      dealer_price: prices.dealer_price,
      mrp: prices.mrp,
      sales_type: classification.sales_type || '',
      product_type: classification.product_type || '',
      image_urls: product.image_urls || [],
      visible_stock: Number(product.visible_stock) || 0,
      in_stock: product.in_stock === true,
      tracks_inventory: product.tracks_inventory === true,
      owner_company_id: product.owner_company_id || product.seller?.id || null,
      seller: product.seller || null,
      added_by_type: product.added_by_type || '',
      can_manage: product.can_manage === true,
      can_enquire: product.can_enquire === true,
    },
    name: product.name || 'Unnamed Product',
    alias: product.alias || '',
    productCode: product.code || '',
    brand: product.brand?.name || '',
    category: product.category?.name || '',
    subCategory: product.sub_category?.name || '',
    size: specs.size || '',
    finish: specs.finish || '',
    tileType: specs.tile_type || '',
    grade: specs.grade || '',
    material: specs.material || '',
    color: specs.color || '',
    thickness: specs.thickness || '',
    application: specs.application || '',
    unit: product.unit || '',
    gstPercent: product.gst_percent,
    retailPrice: retail > 0 ? retail : null,
    mrp: mrp > 0 ? mrp : null,
    dealerPrice: Number(prices.dealer_price) > 0 ? Number(prices.dealer_price) : null,
    pcsPerBox: packing.pcs_per_box || null,
    sqftPerBox: packing.sqft_per_box || null,
    visibleStock: Number(product.visible_stock) || 0,
    inStock: product.in_stock === true,
    tracksInventory: product.tracks_inventory === true,
    ownerCompanyId: product.owner_company_id || product.seller?.id || null,
    seller: product.seller || null,
    addedByType: product.added_by_type || '',
    canManage: product.can_manage === true,
    canEnquire: product.can_enquire === true,
    flags: product.flags || {},
    images: Array.isArray(product.image_urls)
      ? product.image_urls.map(mediaUrl).filter(Boolean)
      : [],
  };
}
